// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ovjplhokmvzjmaeibsjb.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im92anBsaG9rbXZ6am1hZWlic2piIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTYzMjI1OTYsImV4cCI6MjA3MTg5ODU5Nn0.KtGLdjqRp-toA5-2S_4Z0ySJ-CQUPX7g5-v0NrN9vL4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});